name: Build and Deploy to OSS

on:
  workflow_dispatch:
#  push:
#    tags:
#      - "v*"

env:
  APP_NAME: com.ripplestar.miaoyan

jobs:
  deploy:
    runs-on: macos-14
    env:
      ALIYUN_REGION: ${{ vars.ALIYUN_REGION }}
      ALIYUN_OSS_BUCKET_NAME: ${{ vars.ALIYUN_OSS_BUCKET_NAME }}
      ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
      ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      # Apple
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Pnpm
        uses: pnpm/action-setup@v4

      - name: Import Code Signing Certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MACOS_DEVELOPER_ID_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_DEVELOPER_ID_CERTIFICATE_PASSWORD }}

      - uses: aliyun/setup-aliyun-cli-action@v1
      - name: Setup aliyun cli
        run: |
          aliyun configure set --profile default --mode AK --access-key-id $ALIYUN_ACCESS_KEY_ID --access-key-secret $ALIYUN_ACCESS_KEY_SECRET --region $ALIYUN_REGION

      # Build Artifact
      - name: Build
        run: |
          rm -rf release
          cd packages/d-flow-center && pnpm i && pnpm build

      # Upload Artifact
      - name: Upload artifact to OSS
        run: |
          aliyun oss cp packages/d-flow-center/release/ oss://$ALIYUN_OSS_BUCKET_NAME/apps/$APP_NAME/ --recursive
