name: Build and Deploy to staging

on:
  push:
    branches:
      - main
      - staging


env:
  APP_NAME: com.ripplestar.miaoyan

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    env:
      ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
      ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
      ALIYUN_REGION: ${{ vars.ALIYUN_REGION }}
      ALIYUN_OSS_BUCKET_NAME: ${{ vars.ALIYUN_OSS_BUCKET_NAME }}

      # Apple
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          lfs: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Pnpm
        uses: pnpm/action-setup@v4

      - uses: aliyun/setup-aliyun-cli-action@v1
      - name: Setup aliyun cli
        run: |
          aliyun configure set --profile default --mode AK --access-key-id $ALIYUN_ACCESS_KEY_ID --access-key-secret $ALIYUN_ACCESS_KEY_SECRET --region $ALIYUN_REGION

      # Build Artifact
      - name: Build
        run: |
          rm -rf release
          cd packages/d-flow-center && pnpm build

      # Upload Artifact
      - name: Upload artifact to OSS
        run: |
          aliyun oss cp packages/d-flow-center/release/ oss://$ALIYUN_OSS_BUCKET_NAME/$APP_NAME/ --recursive
